version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
    resource_class: medium

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install pidstat for CPU/Memory monitoring
          command: |
            sudo apt-get update
            sudo apt-get install -y sysstat curl
      - run:
          name: Run Everything
          command: |
            START_TIME=$(date +%s)

            # Start monitoring
            echo "Starting pidstat..."
            nohup pidstat -r -u -h 1 > usage.log 2>&1 &
            PIDSTAT_PID=$!
            echo "Started pidstat with PID $PIDSTAT_PID"

            # Simulate actual workload
            echo "Installing dependencies..."
            npm install
            echo "Installing Railway..."
            npm install -g @railway/cli
            echo "Deploying to Railway..."
            railway up --service fab5a752-14e9-4e05-9f95-4499ed6e7cd4 -d || echo "Railway deploy failed"
            echo "Railway deploy finished"
            
            # Stop monitoring
            echo "Stopping pidstat..."
            kill $PIDSTAT_PID || echo "pidstat already stopped"

            # Output results
            END_TIME=$(date +%s)
            echo "=============================="
            echo "Total CI + CD Time: $((END_TIME - START_TIME)) seconds"
            echo "=============================="

            # Output usage log
            if [ -f usage.log ]; then
              echo "==== usage.log ===="
              cat usage.log
            else
              echo "usage.log not found"
            fi

      - store_artifacts:
          path: usage.log
          destination: cpu-memory-usage

workflows:
  ci_cd_pipeline:
    jobs:
      - build-and-deploy
