version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
    resource_class: medium

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Measure CI/CD Start Time
          command: echo "START_TIME=$(date +%s)" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Install pidstat for CPU/Memory monitoring
          command: |
            sudo apt-get update
            sudo apt-get install -y sysstat curl

      - run:
          name: Install Railway
          command: |
            npm install -g @railway/cli

      - run:
          name: Deploy + Monitor Railway
          environment:
            RAILWAY_TOKEN: b3f08ed2-38e9-4d90-beb4-e66080321082
          command: |
            echo "START_TIME=$(date +%s)" >> $BASH_ENV

            railway up --service fab5a752-14e9-4e05-9f95-4499ed6e7cd4 -d > railway.log 2>&1 &
            APP_PID=$!

            echo "Railway PID: $APP_PID"

            pidstat -r -u -p $APP_PID 1 > usage.log &
            PIDSTAT_PID=$!

            wait $APP_PID
            kill $PIDSTAT_PID || true

            echo "PIDSTAT_PID=$PIDSTAT_PID" >> $BASH_ENV

      - run:
          name: Stop Monitoring & Measure End Time
          command: |
            source $BASH_ENV
            kill $PIDSTAT_PID || true

            END_TIME=$(date +%s)
            TOTAL_TIME=$((END_TIME - START_TIME))
            echo "=============================="
            echo "Total CI + CD Time: $TOTAL_TIME seconds"
            echo "=============================="

      - run:
          name: Tes pidstat dengan proses dummy
          command: |
            sleep 10 &
            DUMMY_PID=$!
            pidstat -r -u -p $DUMMY_PID 1 5 > dummy-usage.log
            cat dummy-usage.log



      - store_artifacts:
          path: usage.log
          destination: cpu-memory-usage

workflows:
  ci_cd_pipeline:
    jobs:
      - build-and-deploy

