version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
    resource_class: medium

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Measure CI/CD Start Time
          command: echo "START_TIME=$(date +%s)" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Install pidstat for CPU/Memory monitoring
          command: |
            sudo apt-get update
            sudo apt-get install -y sysstat curl

      - run:
          name: Start Monitoring CPU/Memory
          background: true
          command: |
            pidstat -r -u -h 1 300 > usage.log &
            echo "PIDSTAT_PID=$!" >> $BASH_ENV

      - run:
          name: Deploy to Railway (CD process)
          command: |
            npm install -g @railway/cli
            echo "$RAILWAY_TOKEN" | railway login --ci
            railway up

      - run:
          name: Stop Monitoring & Measure End Time
          command: |
            source $BASH_ENV
            kill $PIDSTAT_PID || true

            END_TIME=$(date +%s)
            TOTAL_TIME=$((END_TIME - START_TIME))
            echo "=============================="
            echo "Total CI + CD Time: $TOTAL_TIME seconds"
            echo "=============================="

      - store_artifacts:
          path: usage.log
          destination: cpu-memory-usage

workflows:
  ci_cd_pipeline:
    jobs:
      - build-and-deploy
